info:
  application:
    name: spring-batch-upload-csv-to-db
    description: Upload CSV to database using spring batch
    profile: generic
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: spring-batch-upload-csv-to-db
    description: Upload CSV to database using spring batch
    profile: generic
  profiles:
    active: dev
  batch:
    job:
      enabled: false
    initialize-schema: ALWAYS