server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
spring:
  datasource:
    url: jdbc:h2:mem:spring-batch-upload-csv-to-db
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
  sql:
    init:
      mode: always
  application:
    name: spring-batch-upload-csv-to-db
    description: Upload CSV to database using spring batch
    profile: dev
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: false
    initialize-schema: ALWAYS